spring:
  application:
    name: java-ledger-api
  data:
    web:
      pageable:
        max-page-size: 100
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}

jwt:
  access-token-expiration-ms: 900000        # 15 minutes

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
