spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ledger
    username: ledger_user
    password: ledger_pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true



